// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Z0vVBeCY8JF2mCB0rld7-ykh6Ej9TLc',
    appId: '1:292364974425:web:d4c09fb2ac511ad92a3448',
    messagingSenderId: '292364974425',
    projectId: 'prontuario-flutter',
    authDomain: 'prontuario-flutter.firebaseapp.com',
    storageBucket: 'prontuario-flutter.firebasestorage.app',
    measurementId: 'G-VYXKBSXJGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY_v0W904VvC5tOTA9XAefyjoLsSSsZ50',
    appId: '1:292364974425:android:05607af3572eb3472a3448',
    messagingSenderId: '292364974425',
    projectId: 'prontuario-flutter',
    storageBucket: 'prontuario-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA01Brr_SK5R8Wq_E2wjWy79d2fSjOFiMQ',
    appId: '1:292364974425:ios:9f13dc610bfe521d2a3448',
    messagingSenderId: '292364974425',
    projectId: 'prontuario-flutter',
    storageBucket: 'prontuario-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA01Brr_SK5R8Wq_E2wjWy79d2fSjOFiMQ',
    appId: '1:292364974425:ios:9f13dc610bfe521d2a3448',
    messagingSenderId: '292364974425',
    projectId: 'prontuario-flutter',
    storageBucket: 'prontuario-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Z0vVBeCY8JF2mCB0rld7-ykh6Ej9TLc',
    appId: '1:292364974425:web:60ebea2ab22e9f572a3448',
    messagingSenderId: '292364974425',
    projectId: 'prontuario-flutter',
    authDomain: 'prontuario-flutter.firebaseapp.com',
    storageBucket: 'prontuario-flutter.firebasestorage.app',
    measurementId: 'G-YXS39MXX3F',
  );
}
